development:
  adapter: postgresql
  encoding: unicode
  database: hotels_development
  username: hotels
  password:
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: hotels_test
  username: hotels
  password:
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: rails
  username: rails
  password: 
  pool: 5

cucumber:
  <<: *test